stages:
    - build_gaml
    - kafka_host
    - build_generator
    - build_collector
    - build_estimator
    - build_predictor

services:
    - docker:dind

build_gaml_job:
    stage: build_gaml
    tags:
        - docker
    image: docker:latest
    script:
        - cd docker
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/gaml -f Dockerfile_gaml  .
        - docker push $CI_REGISTRY_IMAGE/gaml


buil_kafka_job :
    stage : kafka_host
    tags:
        - docker
    image : docker:latest
    script:
        - cd docker
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/kafka -f Dockerfile_kafka  .
        - docker push $CI_REGISTRY_IMAGE/kafka
#        - docker run --rm -it --network host zookeeper
#        - docker build --no-cache -t tim0bis/tweetoscope_project_2021:kafka -f docker/Dockerfile_kafka .
#        - docker run --rm -it --network host tim0bis/tweetoscope_project_2021:kafka

buil_generator_job :
    stage : build_generator
    tags:
        - docker
    image : docker:latest
    script:
        - cd docker
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/generator -f Dockerfile_generator  .
        - docker push $CI_REGISTRY_IMAGE/generator
#        - docker build --no-cache -t tim0bis/tweetoscope_project_2021:generator -f docker/Dockerfile_generator .

buil_collector_job :
    stage : build_collector
    tags:
        - docker
    image : docker:latest
    script:
        - cd docker
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/collector -f Dockerfile_collector  .
        - docker push $CI_REGISTRY_IMAGE/collector
#        - docker build --no-cache -t tim0bis/tweetoscope_project_2021:collector -f docker/Dockerfile_collector .

buil_collector_job :
    stage : build_estimator
    tags:
        - docker
    image : docker:latest
    script:
        - cd docker
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/estimator -f Dockerfile_estimator  .
        - docker push $CI_REGISTRY_IMAGE/estimator