stages:
    - build_gaml
    - build_collector
    - build_estimator
    - build_predictor

  services:
    - docker:dind

build_package_job:
    stage: build_gaml
    tags:
        - docker
    image: docker:latest
    script:
        - docker build -t tim0bis/tweetoscope_project_2021:gaml -f docker/Dockerfile_gaml .
        - docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PWD $DOCKERHUB
        - docker push tim0bis/tweetoscope_project_2021:gaml
