apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      name: generator-pod
      labels:
        app: generator
    spec:
      containers:
      - name: generator-container
        image: gitlab-student.centralesupelec.fr/hamza.benslimane/tweetoscope_2021_07/generator
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      name: collector-pod
      labels:
        app: collector
    spec:
      containers:
      - name: collector-container
        image: gitlab-student.centralesupelec.fr/hamza.benslimane/tweetoscope_2021_07/collector
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: estimator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estimator
  template:
    metadata:
      name: estimator-pod
      labels:
        app: estimator
    spec:
      containers:
      - name: estimator-container
        image: gitlab-student.centralesupelec.fr/hamza.benslimane/tweetoscope_2021_07/estimator
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      name: predictor-pod
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor-container
        image: gitlab-student.centralesupelec.fr/hamza.benslimane/tweetoscope_2021_07/predictor
        imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner
  template:
    metadata:
      name: learner-pod
      labels:
        app: learner
    spec:
      containers:
      - name: learner-container
        image: gitlab-student.centralesupelec.fr/hamza.benslimane/tweetoscope_2021_07/learner
        imagePullPolicy: Always
