FROM python:3.8-slim

# Set time
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#Python Libraries
RUN pip install --upgrade pip
RUN pip3 install numpy
RUN pip3 install kafka-python
RUN pip3 install pandas
RUN pip3 install termcolor
RUN pip3 install scikit-learn
RUN apt update

### Adding files ###
ADD ./learner.py .
ADD ./logger.py .
ADD ./Predictor.py .

### Running command ###
CMD python3 learner.py