FROM tim0bis/tweetoscope_project_2021:gaml

#in gaml we have : ubuntu basis, kafka, gaml

# See https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#C++ requirements for collector

#Adding files
