FROM python:3.8-slim

### Librairies installations ###

RUN pip install --upgrade pip
RUN pip3 install numpy \
scipy \
matplotlib \
pandas \
seaborn \
kafka-python \
termcolor

### Adding files ###

ADD ./tweetoscope_2021_07/estimator/estimator.py .
ADD ./tweetoscope_2021_07/estimator/estimator_header.py .
ADD ./tweetoscope_2021_07/estimator/cosumer_setup.py .

### Running command ###
CMD python3 estimator.py --broker-list kafka-service:9092