FROM tim0bis/tweetoscope_project_2021:gaml

#in gaml we have : ubuntu basis, kafka, gaml

# Set time
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#C++ requirements for collector


#Adding files
ADD ./tweetoscope_2021_07/params.config .
ADD ./tweetoscope_2021_07/tweet-generator .

#Running generator
RUN ./tweet-generator generator.params