FROM ubuntu

# See https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#Basic req
RUN apt-get update -y
RUN apt-get install dialog apt-utils -y

RUN apt-get install wget -y
RUN apt-get install git -y
RUN apt-get install cmake -y
RUN apt-get install make -y

RUN apt-get install gcc-7 g++-7 -y

RUN apt-get install -y build-essential 
RUN apt-get install -y pkg-config 
RUN apt-get install -y python-dev 
RUN apt-get install -y python-six 
RUN apt-get install -y cython 
RUN apt-get install -y python-numpy 
RUN apt-get install -y coinor-libipopt1v5 
RUN apt-get install -y coinor-libipopt-dev
RUN apt-get update -y

#C++

#GAML
#RUN echo "Installing GAML.."
RUN git clone https://github.com/HerveFrezza-Buet/gaml
WORKDIR /gaml/gaml/build
RUN cmake .. -DCMAKE_INSTALL_PREFIX=/usr
RUN make -j
RUN make install
WORKDIR /


# CPPKAFKA
#RUN echo "Installing kafka.."
RUN apt-get install -y librdkafka-dev
RUN apt-get install -y libssl-dev
RUN apt-get install -y build-essential libboost-all-dev
RUN git clone https://github.com/mfontanini/cppkafka.git
RUN cd cppkafka; mkdir build; cd build; cmake .. -DCMAKE_INSTALL_PREFIX=/usr; make install -j
ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/lib/x86_64-linux-gnu"