FROM python:3.8-slim

# Set time
ENV TZ=Europe/Paris
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

#Python Libraries
RUN pip install --upgrade pip
RUN pip3 install json \
termcolor \
kafka-python

### Adding files ###

WORKDIR /tweetoscope_2021_07/
ADD ./estimator/logger.py .

### Running command ###
CMD python3 logger.py 