FROM tim0bis/tweetoscope_project_2021:gaml

ADD ./kafka_2.13-2.4.1 .
ADD ./kafka.sh .

ENV KAFKA_PATH=./
RUN chmod +x ./kafka.sh
CMD ./kafka.sh start --zooconfig zookeeper.properties --serverconfig server.properties